language: python

branches:
    only:
        - master

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8

# a list of commands to run before the main script
before_script:
    - "flake8 codebase"

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls